#!/bin/bash
###############################################################################
# Copyright (C) 2011 Sang Chul Choi
#
# This file is part of Mauve Analysis.
# 
# Mauve Analysis is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Mauve Analysis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Mauve Analysis.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################

BASEDIR=output/virulence


# Create a table.
perl pl/virulence.pl table \
  -virulence $BASEDIR/virulent_genes.txt \
  -ortholog $BASEDIR/fam-frag2.part.txt \
  -out $BASEDIR/table.txt
exit

# Create the virulence output directory.
mkdir $BASEDIR

# Copy files from streptococcus project directory at swiftgen.
scp -q swiftgen:/usr/projects/strep/gainloss/config/fam-frag2.part.txt $BASEDIR
scp -q swiftgen:/usr/projects/strep/gainloss/config/strep.smap $BASEDIR
scp -q swiftgen:/usr/projects/strep/virulent_genes.txt $BASEDIR

#############################################################
# Create virulence genes in BED format.
PTTFILE=/Volumes/Elements/Documents/Projects/mauve/bacteria/Streptococcus_pyogenes_MGAS315_uid57911/NC_004070.ptt
perl pl/virulence.pl bed \
  -virulence $BASEDIR/virulent_genes.txt \
  -ptt $PTTFILE \
  -out $BASEDIR/spy1.bed
echo "Check $BASEDIR/spy1.bed"
hgLoadBed SpyMGAS315 virulence $BASEDIR/spy1.bed
exit


